@startuml Init_device
title "Struct set_prog_start"
class set_prog_start {
  string name;
  string executable_path;
  string stdout_config_file;
  bool stdout_config_truncate;
  int run_prog;
  vector<string> cmd_arguments;
}

@enduml